### ISSUE TITLE
Labels image and labels_list

### ISSUE THREAD

**Issue by qtalwaysrun** [scilus/connectoflow#5]
Hello, 
Thank you so much for creating this great pipeline!
Now I am using Connectoflow pipeline to create networks. For the labels_.nii.gz image,  I used the aparc+aseg image (using Desikan-Killiany atlas) from Freesurfer as the labels image. The labels for aparc+aseg image should include cortical and subcortical regions.

In the beginning, for the labels_list, I just used the ctx-regions corresponding integers (1000~1035,2000~2035) but I can't get the matrix (the .log file notes that: Empty matrix, no entries to save); at the same time, I found in one of the results files (Average_Connections), which seems to average the streamlines between any pair of two subcortical regions, so the second time I just put the subcortical integers (2,4,5,7,8…,77, 85,251...255) in the label list, and this time I can get the matrix. 

I was wondering why the pipeline can not get the connectivity between the cortical regions, or maybe the label image (aparc+aseg) I provided was not the right one?

Thank you so much!

**Comment by mdesco** [comment]
You must make sure your labels only contain cortical and subcortical labels. You must remove all other labels (CSF, wm, etc...) labels. 

@frheault can you help him?

**Comment by qtalwaysrun** [comment]
Thank you very much!   I have fixed this issue!
Have a good day!
